// const path = __dirname + '/input_boj3.txt'
const path = '/dev/stdin'

const input = require('fs')
.readFileSync(path)
.toString()
.trim()

if (input === "1995") console.log("ITMO")
else if (input === "1996") console.log("SPbSU")
else if (input === "1997") console.log("SPbSU")
else if (input === "1998") console.log("ITMO")
else if (input === "1999") console.log("ITMO")
else if (input === "2000") console.log("SPbSU")
else if (input === "2001") console.log("ITMO")
else if (input === "2002") console.log("ITMO")
else if (input === "2003") console.log("ITMO")
else if (input === "2004") console.log("ITMO")
else if (input === "2005") console.log("ITMO")
else if (input === "2006") console.log("PetrSU, ITMO")
else if (input === "2007") console.log("SPbSU")
else if (input === "2008") console.log("SPbSU")
else if (input === "2009") console.log("ITMO")
else if (input === "2010") console.log("ITMO")
else if (input === "2011") console.log("ITMO")
else if (input === "2012") console.log("ITMO")
else if (input === "2013") console.log("SPbSU")
else if (input === "2014") console.log("ITMO")
else if (input === "2015") console.log("ITMO")
else if (input === "2016") console.log("ITMO")
else if (input === "2017") console.log("ITMO")
else if (input === "2018") console.log("SPbSU")
else if (input === "2019") console.log("ITMO")
